### ISSUE TITLE
segmentation fault with Data::Printer

### ISSUE THREAD

**Issue by hhg7** [niner/Inline-Perl5#130] opened 2019-02-20 03:23 UTC
Hi,

I encountered a segmentation fault in Perl6 when trying to run `use Data::Printer:from<Perl5>` on data that should look like this (from Perl5).  The data itself is very very small, only 15 strings on a hash of array.
```

{
    21    [
        [0] "format2_RRBS_P21_1.txt",
        [1] "format2_RRBS_P21_3.txt",
        [2] "format2_RRBS_P21_2.txt"
    ],
    28    [
        [0] "format2_RRBS_P28_2.txt",
        [1] "format2_RRBS_P28_3.txt",
        [2] "format2_RRBS_P28_1.txt"
    ],
    40    [
        [0] "format2_RRBS_P40_3.txt",
        [1] "format2_RRBS_P40_1.txt",
        [2] "format2_RRBS_P40_2.txt"
    ],
    60    [
        [0] "format2_RRBS_P60_2.txt",
        [1] "format2_RRBS_P60_3.txt",
        [2] "format2_RRBS_P60_1.txt"
    ],
    180   [
        [0] "format2_RRBS_P180_1.txt",
        [1] "format2_RRBS_P180_2.txt",
        [2] "format2_RRBS_P180_3.txt"
    ]
}
```

I build the data like this in Perl6:
```
CONTROL {
	when CX::Warn {
		note $_;
		exit 1;
	}
}
use fatal;
role KeyRequired {
	method AT-KEY (\key) {
		die "Key {key} not found" unless self.EXISTS-KEY(key);
		nextsame;
	}
}

for dir(test => /^format2_RRBS_P\d.+<[1..3]>\.txt$/) -> $input {
	put $input;
	my $group;
	if $input ~~ m:P5/P(\d{2,3})/ {
		$group = $0;
	} else {
		put "$input failed regex.";
		die
	}
	%input{$group}.append: $input;
}

use Data::Printer:from<Perl5>;
p %input;```

**Comment by niner** [comment] 2019-02-23 10:23
I'm sorry, I haven't been able to reproduce the segfault. It seems like the code you posted is incomplete. There's for example no declaration of %input and the KeyRequired role is not used anywhere.

Can you please post a complete example that I can run on my machine and that reproduces the issue? A backtrace with debug symbols could also help, but if I'm able to reproduce here, I can get that easily myself.

**Comment by hhg7** [comment] 2019-02-24 16:21
Hi @niner 

this is what the hash of array is supposed to look like in JSON:

the hash can be build thus in Perl6:

```
my %i;
%i<21> = 'format2_RRBS_P21_1.txt','format2_RRBS_P21_3.txt','format2_RRBS_P21_2.txt';
%i<180> = 'format2_RRBS_P180_1.txt','format2_RRBS_P180_2.txt','format2_RRBS_P180_3.txt';
%i<60> = 'format2_RRBS_P60_2.txt','format2_RRBS_P60_3.txt','format2_RRBS_P60_1.txt';
%i<28> = 'format2_RRBS_P28_2.txt','format2_RRBS_P28_3.txt','format2_RRBS_P28_1.txt';
%i<40> = 'format2_RRBS_P40_3.txt','format2_RRBS_P40_1.txt','format2_RRBS_P40_2.txt';
```

this works, but when I build the hash using `%i{$group}.append: $input;` it shows the following JSON
```

{
  "21": [
    {
      "0": null
    },
    {
      "0": null
    },
    {
      "0": null
    }
  ],
  "180": [
    {
      "0": null
    },
    {
      "0": null
    },
    {
      "0": null
    }
  ],
  "60": [
    {
      "0": null
    },
    {
      "0": null
    },
    {
      "0": null
    }
  ],
  "28": [
    {
      "0": null
    },
    {
      "0": null
    },
    {
      "0": null
    }
  ],
  "40": [
    {
      "0": null
    },
    {
      "0": null
    },
    {
      "0": null
    }
  ]
}
```
I only found out about this through Data::Printer, but now it doesn't sound like an issue in Inline::Perl5, why would Perl6 do this?

**Comment by niner** [comment] 2019-11-19 07:08
I'm sorry, I still cannot reproduce the segmentation fault, even with the test file as listed below. It may well be the segfault was fixed in the meantime in MoarVM or Inline::Perl5.

Please feel free to reopen this issue if you have a way to reproduce this on current rakudo and Inline::Perl5!

```
my %input; 
%input<21> = 'format2_RRBS_P21_1.txt','format2_RRBS_P21_3.txt','format2_RRBS_P21_2.txt';                         
%input<180> = 'format2_RRBS_P180_1.txt','format2_RRBS_P180_2.txt','format2_RRBS_P180_3.txt';                     
%input<60> = 'format2_RRBS_P60_2.txt','format2_RRBS_P60_3.txt','format2_RRBS_P60_1.txt';
%input<28> = 'format2_RRBS_P28_2.txt','format2_RRBS_P28_3.txt','format2_RRBS_P28_1.txt';                         
%input<40> = 'format2_RRBS_P40_3.txt','format2_RRBS_P40_1.txt','format2_RRBS_P40_2.txt';                         
CONTROL {                                                                                                        
        when CX::Warn {
                note $_;
                exit 1;
        }                                                                                                        
}       
use fatal;  
role KeyRequired { 
        method AT-KEY (\key) {                                                                                   
                die "Key {key} not found" unless self.EXISTS-KEY(key);                                           
                nextsame;                                                                                        
        }
}                                                                                                                
    
for dir(test => /^format2_RRBS_P\d.+<[1..3]>\.txt$/) -> $input {
        put $input;
        my $group;
        if $input ~~ m:P5/P(\d{2,3})/ {
                $group = $0;
        } else {
                put "$input failed regex.";                                                                      
                die                                                                                              
        }
        %input{$group}.append: $input;                                                                           
}           
                
use Data::Printer:from<Perl5> 'show_tied', 0;                                                                    
p %input;
```

**Closed by niner** 2019-11-19 07:08 UTC
