### ISSUE TITLE
Mojo::DOM::to_string returns an empty string

### ISSUE THREAD

**Issue by hoelzro** [niner/Inline-Perl5#13] opened 2015-02-24 03:14 UTC
This is probably something with the particulars of how that method works, but I figured it may be indicative of something that `Inline::Perl5` can do.

Example code:

```perl
# Perl 5

use strict;
use warnings;
use feature qw(say);

use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new;
$ua->max_redirects(5);

my $res = $ua->get('http://dgg.gg')->res;
say $res->dom->to_string; # prints the full HTML body
```

```perl6
# Perl 6
use v6;

use Inline::Perl5;
use Mojo::UserAgent:from<Perl5>;

my $ua = Mojo::UserAgent.new;
$ua.max_redirects(5);

my $res = $ua.get('http://ddg.gg').res;
say $res.dom.to_string; # prints the empty string
```

**Comment by niner** [comment] 2015-07-19 08:19
I cannot reproduce this anymore with current Inline::Perl5. Seems to be fixed with:

commit e8589a5a2ab71877bdefc823ba478613588d2812
Author: Stefan Seifert <nine@detonation.org>
Date:   Thu Apr 16 14:48:07 2015 +0200

    Fix passing strings containing NULL bytes from P6 to P5.

**Closed by niner** 2015-07-19 08:19 UTC

**Comment by hoelzro** [comment] 2015-07-19 14:21
@niner Thanks for looking into this, but I still see the issue with Inline::Perl5 07dd4fb.  You get all of the output from `$res.dom.to_string`?  I'll dig into this issue and see what's going on with my machines!
